version: '2.0'
services:
  mysql:
    container_name: mysql
    restart: always
    image: mysql/mysql-server
    ports:
      - 3306:3306
    command: --default-authentication-plugin=mysql_native_password
    environment:
      - MYSQL_ROOT_PASSWORD=123456
    volumes:
      - "./script/:/docker-entrypoint-initdb.d/"
